### ISSUE TITLE
Error when using a keyboard layout with special characters

### ISSUE THREAD

**Issue by edubart** [cartesi/opensbi#2]
## Context

If I switch my keyboard layout to a PR-BR layout, and type any special character in our emulator while interactive mode, I get the following error:

```
sbi_ecall_handler: Invalid error -89 for ext=0x2 func=0x0
```

**Comment by edubart** [comment]
Looks like this was fixed in OpenSBI v1.3, in commit https://github.com/riscv-software-src/opensbi/commit/f5dfd991396891d87d7780be45f887bc9ed13099

**Comment by vfusco** [comment]
We already migrated to opensbi 1.3.1
